remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [43c]
description: [We make games]

google_analytics: [Your Google Analytics tracking ID]